@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as Actor
participant CancelMeetingUI as UI <<presentation>>



Actor --> UI: Cancel a meeting
activate UI


        UI --> Actor: shows all meetings
        Actor --> UI: choose a meeting to cancel
        UI-->Actor



deactivate UI
@enduml