@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor Manager as Actor
participant DecativateUserUI as UI <<presentation>>



Actor --> UI: Activate User
activate UI

        UI-->Actor: list deactivated users

        Actor --> UI : selects user

         UI --> Actor : displays success


deactivate UI
@enduml