@startuml
autonumber

actor "Teacher" as Tea

activate Tea

Tea -> ":System": asks to schedule a class
activate ":System"
Tea <-- ":System": shows the list of Courses
deactivate ":System"

Tea -> ":System":selects a Course
activate ":System"
Tea <-- ":System": requests data: (title, date, hour, duration of the class)
deactivate ":System"

Tea -> ":System":types requested data
activate ":System"
Tea <-- ":System":shows all data and requests confirmation
deactivate ":System"

Tea -> ":System":confirms the data
activate ":System"
Tea <-- ":System":informs operation success
deactivate ":System"

deactivate Tea

@enduml
