@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor Manager as Actor
participant CloseCourseUI as UI <<presentation>>



Actor --> UI: Close course
activate UI

        UI-->Actor: list non-closed courses

        Actor --> UI : selects course

         UI --> Actor : displays success


deactivate UI
@enduml