@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten false
skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as Actor
participant CreatePostItOnBoardUI as UI <<presentation>>
Actor -> UI: Create PostIt on a Board
activate UI
UI --> Actor: lists the boards with write permissions
Actor -> UI: selects a board
UI --> Actor : shows availableCells in board
Actor -> UI: selects a cell to post
UI --> Actor: asks PostIt content
Actor -> UI: inputs the PostIt content
UI --> Actor: displays success
@enduml

