@startuml

scale 200 width
hide empty description

skinparam state {
    BackgroundColor White
    BorderColor Black
}

[*] --> Requested : Enrollment
Requested --> Accepted
Requested --> Rejected
Accepted --> [*]
Rejected --> [*]

@enduml
