@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false


participant RequestEnrollmentController as Controller <<application>>
participant CourseManagementService as courseSvc <<application>>
participant PersistenceContext as Persistence <<persistence>>
participant AppSettings as set
participant RepositoryFactory as Factory <<factory>>
database CourseRepository as Repository <<repository>>

Controller -> courseSvc : create()
activate courseSvc
Controller -> courseSvc : enrollCourses()
courseSvc   -> Persistence : repositories()
activate Persistence
Persistence -> set: instance()
Persistence -> set: getRepositoryFactory()
deactivate Persistence
activate set
set --> Factory: create
activate Factory
Factory --> set
deactivate Factory
set --> courseSvc
deactivate set
courseSvc -> Factory: enrollingCourses()
activate Factory
Factory --> Repository: enrollingCourses()
courseSvc -> Repository: coursesByState = findByEnrollState()
activate Repository
Repository --> courseSvc
deactivate Repository
courseSvc --> Controller
deactivate Controller

@enduml